apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-app

  labels:

    app: nginx

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todo

  template:

    metadata:

      labels:

        app: todo

    spec:

      containers:

      - name: todo-app

        image: ubaid004/kubernetes:v1

        ports:

        - containerPort: 80

